server:
  port: ${SERVER_PORT}

logging:
  level:
    root: info
    me.sonam.auth: info
    org.springframework.web: info
    org.springframework.security: info
    org.springframework.security.oauth2: info
    org.springframework.boot.autoconfigure: warn

spring:
  application:
    name: oauth2-token-mediator
  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_SERVICE}/${POSTGRES_DBNAME}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    properties:
      sslMode: ${DB_SSLMODE}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URL}

issuerUrl: ${ISSUER_URL}

authorization:
  root: ${ISSUER_URL}
  authorize: /oauth2/authorize
  token: /oauth2/token

permitpath:
  - path: /oauth2-token-mediator/api/health/*
  - path: /oauth2-token-mediator/authorize
    httpMethods: GET
  - path: /oauth2-token-mediator/token

password: ${CLIENT_SECRET_PASSWORD}

token:
  audiences: ${OAUTH_CLIENTS}
  issuerUri: ${ISSUER_URL}