# This yaml file is for loading local database, server port, disable eureka and set jwt-rest-service endpoint
SERVER_PORT: 8087

POSTGRES_USERNAME: test
POSTGRES_PASSWORD: test
POSTGRES_DBNAME: token-mediator
POSTGRES_SERVICE: localhost:5432
DB_SSLMODE: disable

EUREKA_HOST: localhost:8761
EUREKA_USER: test
EUREKA_PASSWORD: test

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://${EUREKA_USER}:${EUREKA_PASSWORD}@${EUREKA_HOST}/eureka

OAUTH_CLIENTS: nextjs-client, oauth-client
ISSUER_URL: http://api-gateway:9001/issuer

CLIENT_SECRET_PASSWORD: IforTibet
spring:
  cloud:
    kubernetes:
      enabled: false


